{% set name = "abi3audit" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/abi3audit-{{ version }}.tar.gz
  sha256: b2768ecaad4118432fc79b354e86f141a063150ae046a16490dd2f995c61e816

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - abi3audit = abi3audit._cli:main"

requirements:
  host:
    - flit-core >=3.2,<4
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - abi3info >=2023.01.27
    - kaitaistruct >=0.10,<1.dev0
    - packaging >=21.3,<24.0
    - pefile >=2022.5.30
    - pyelftools >=0.29
    - requests >=2.28.1,<2.29.dev0
    - requests-cache >=0.9.6,<0.10.dev0
    - rich >=12.5.1,<13.4.0

test:
  imports:
    - abi3audit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/abi3audit/
  summary: Scans Python wheels for abi3 violations and inconsistencies
  dev_url: https://github.com/trailofbits/abi3audit
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
